### ISSUE TITLE
Setting due date in schedule does not set due date on problem

### ISSUE THREAD

**Issue by pdpinch** [mitocw/edx-platform#100]
Steps to Reproduce

1. Create a sub-section in a master course in studio
2. Create multiple units in the sub-section with multiple problems
2. Set the due date for the sub-section to be in the past
3. Publish the section and, in student view, confirm that the `Check` button is not available on all the problems in the sub-section
4. Create a CCX based on the master course
5. Add the sub-section you created above
3. Set the Due Date for the sub-section (as you would in Studio) to be a date in the past
4. View the CCX as a student

**Expected Behavior:**
`Check` button is not available on all the problems in the sub-section

**Acutal Behavior:**
`Check` button *is* available on all the problems in the sub-section. In effect, there is no due date.

**Comment by amir-qayyum-khan** [comment]
@giocalitri why not i do this task, because i am already working on schedule. https://github.com/mitocw/edx-platform/pull/99

What you say?

**Comment by giocalitri** [comment]
I'm fine with that, even if @pdpinch the 2 stories are not strictly related

**Comment by amir-qayyum-khan** [comment]
@pdpinch  Fixed via commit https://github.com/mitocw/edx-platform/commit/593be94c04a03ad62e278551dc38837a91328754#diff-b365e6e4f2d48b57c4e934dbd230e3e4R937

**Comment by amir-qayyum-khan** [comment]
I found that ccx was not overriding start and due dates of problems/components of unit.
So in PR #99 on saving ccx schedule I am now updating dates of each problem in a vertical.
After this solution you can control due dates via schedule for a ccx course.

**Comment by pdpinch** [comment]
I think it would be a good idea to leave this as a separate commit on PR #99. Don't squash it unless edX really wants you to.

**Comment by amir-qayyum-khan** [comment]
ok sure

**Comment by pdpinch** [comment]
closed via edx#10619
