### ISSUE TITLE
New accounts created via CAS don't create user profiles

### ISSUE THREAD

**Issue by pdpinch** [mitocw/edx-platform#102]
This can be easily reproduced by going to https://partners.mitx.mit.edu/ and creating a new Touchstone collaboration account to log in. 

via [ZenDesk #2534](https://odl.zendesk.com/agent/tickets/2534):

> The profile needs to be explicitly generated everywhere in the platform where a user object is created. In the CAS code, we're probably not hitting any code paths where user profiles are generated.

> Marked this as low priority because it doesn't cause any service interruption, but it likely causes brief confusion from the user's perspective since they get a 500.

> This can be easily reproduced by creating a new touchstone collaboration account, logging into it, and then visiting partners.

**Comment by pdpinch** [comment]
Testing is a little tricky. You will have to set up a CAS service and turn on the CAS feature flag. The problem currently manifests in cypress. We're not sure if it's been fixed in Dogwood.

**Comment by pwilkins** [comment]
The CAS repo is here: https://github.com/mitocw/django-cas-provider

**Comment by pdpinch** [comment]
Hey @amir-qayyum-khan I wanted to check if you've started this at all?

**Comment by amir-qayyum-khan** [comment]
@pdpinch produced issue
- I made a new account use touchstone collaborator account
- When I login it said.

![screen shot 2016-03-04 at 4 38 16 pm](https://cloud.githubusercontent.com/assets/10431250/13526105/87570292-e227-11e5-8a64-744df1018644.png)

- When i tried to logout, it is not logging me out.

**Comment by pdpinch** [comment]
That's exactly the error. I think you'll find that if you try another URL in the edX app (one that doesn't hit the user profile) you'll be be able to access it.

I put a copy of the stack trace you generated at https://gist.github.com/pdpinch/bd2e626df27a0ccad194 <https://gist.github.com/pdpinch/bd2e626df27a0ccad194>

I believe the problem is that the code in https://github.com/edx/edx-platform/blob/master/common/djangoapps/external_auth/views.py <https://github.com/edx/edx-platform/blob/master/common/djangoapps/external_auth/views.py> automatically creates a user, but it doesn't create a user profile. 

FYI @bdero

**Comment by amir-qayyum-khan** [comment]
@pdpinch should i close this issue, because https://github.com/edx/edx-platform/pull/11988 is merged and release on edX platform

**Comment by pdpinch** [comment]
@bdero, we'll need to cherry pick this fix into our dogwood release.
