### ISSUE TITLE
Annotations: architecture for commenting system

### ISSUE THREAD

**Issue by pdpinch** [mitocw/edx-platform#113]
Comments are attached to an annotation, not to the document itself. This way we can use a generic commenting system. 

Can we reuse edX Discussion API as the commenting component of the annotation?

(Need links to Discussion API docs + code)

**Comment by justinabrahms** [comment]
https://docs.google.com/a/abrah.ms/document/d/1vG6nAIRHgDdEnqr7f4Y28IluEYdxU6XX6qulaZF52W8/edit?usp=docslist_api

On Monday, October 19, 2015, Peter Pinch <notifications@github.com> wrote:

> Assigned #113 <https://github.com/mitocw/edx-platform/issues/113> to
> @justinabrahms <https://github.com/justinabrahms>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mitocw/edx-platform/issues/113#event-439467451>.
>


-- 
Sent via mobile phone.

**Comment by justinabrahms** [comment]
Updated with API endpoint specific things.

**Comment by pdpinch** [comment]
@justinabrahms do you think we can close this now?

**Comment by justinabrahms** [comment]
Yes. I'll mark this as done.
