### ISSUE TITLE
CCX display name should override course display name when view coach dashboard

### ISSUE THREAD

**Issue by pwilkins** [mitocw/edx-platform#115]
This issue came up in the context of discussing providing a single coach with multiple CCXs on the same course.  When a coach has multiple CCXs, the coach should be able to determine which CCX they are working on.  (This isn't a problem when a coach has only one CCX.)

@pdpinch  believes that the CCX name should display in the current CCX release, hence the `bug` label.

**Comment by pdpinch** [comment]
I believe one way to fix this would be to address #33

**Comment by pdpinch** [comment]
It appears that the course name override isn't being applied in the header template.

**Comment by amir-qayyum-khan** [comment]
@pwilkins is this solution ok

CCX Coach Dashboard - ( put CCX display name here)

or any other location you want me to display ccx name?

cc @pdpinch

**Comment by pdpinch** [comment]
When logged in as a coach, the CCX's overridden display_name is used in the student dashboard:

<img width="903" alt="screen shot 2015-10-29 at 10 23 50 am" src="https://cloud.githubusercontent.com/assets/430126/10822389/6f2857c4-7e2d-11e5-8510-403fd6c84141.png">

And the overridden display_name is used in the courseware:

<img width="1327" alt="screen shot 2015-10-29 at 11 29 25 am" src="https://cloud.githubusercontent.com/assets/430126/10823160/b6e7828a-7e30-11e5-854e-c9bc23ba8e1e.png">

BUT the overridden display_name is *not* used when the coach is viewing the CCX dashboard:

<img width="1327" alt="screen shot 2015-10-29 at 11 11 02 am" src="https://cloud.githubusercontent.com/assets/430126/10823176/cc5e31d6-7e30-11e5-8701-7503baf59ff3.png">

**Comment by pwilkins** [comment]
How does this design solution work when a coach has multiple CCXs on the same master course?  Which CCX name do you display in the banner?  I like @amir-qayyum-khan's idea of putting it in the CCX Coach Dashboard if only because the logic is simpler.

**Comment by pdpinch** [comment]
The display name should match the CCX indicated in the URL.

If you think the UX would benefit from also displaying the CCX name inside the dashboard, I'm ok with that --  in addition to the changing the header. 

We don't have a UI yet for multiple CCXs from the same master course, but IMO it should not come from a CCX URL.

**Comment by pwilkins** [comment]
You're right, I was thinking too far ahead.  I agree that for now the display name should match the CCX indicated in the URL.

**Comment by pdpinch** [comment]
@amir-qayyum-khan is this fixed by edx#10672 ?

**Comment by amir-qayyum-khan** [comment]
No, there is a change. I will fix it in another PR. This is out of scope of that PR

**Comment by amir-qayyum-khan** [comment]
Fixed via https://github.com/edx/edx-platform/pull/10877

**Comment by amir-qayyum-khan** [comment]
merged in master via ccx PR https://github.com/edx/edx-platform/pull/11787
