### ISSUE TITLE
Add course advanced setting for CCX Connector

### ISSUE THREAD

**Issue by pdpinch** [mitocw/edx-platform#118]
As a course admin (instructor) I need a way to indicate that my course is available to a CCX connector and the end point for the CCX Connector. 

As an initial implementation, this can be done as an advanced setting on the course (similar to `enable_ccx`). The key should be `ccx_connector` and the name should be "CCX Connector URL" The help text should be "URL for CCX Connector application for managing creation of CCXs. (optional)"

The connector end point will need to be discoverable via an API call, perhaps to the Course Structure API  (need link). 

We don't want to submit a PR to edX until we have had more product discussions with them. But we will need this for development of the CCX Connector application (need link).

**Comment by amir-qayyum-khan** [comment]
@pdpinch So we need here a setting in course ```advance setting``` a string that input a url?
 And do you want that ccx coach can access to that url from dashboard?

**Comment by pdpinch** [comment]
Yes, we need to add an advanced setting for inputting a URL string. 

No, we don't want the coach to access it. This will be set by the course instructor/admin in studio.

**Comment by amir-qayyum-khan** [comment]
ok- after setting this think in course database, how you going to utilise it? who will use this end point?

**Comment by pdpinch** [comment]
We will do one of the following:

1. Whenever a CCX is created based on the course, we will post to the CCX Connector so it can build an inventory of courses available for CCXs
2. We will expose the endpoint in a course info API (haven't determined which one) so the CCX connector can poll an open edX installation for courses that are available to it.

**Comment by pdpinch** [comment]
We need to store a secret as well as the URL endpoint -- similar to LTI.

**Comment by amir-qayyum-khan** [comment]
fixed via https://github.com/edx/edx-platform/pull/10931
