### ISSUE TITLE
Provide an API endpoint on edx that enables adding CCX courses programmatically

### ISSUE THREAD

**Issue by pdpinch** [mitocw/edx-platform#119]
When users (teachers) purchase a course, or course components, the corresponding CCX needs to be created on a particular edX instance. 

to create a course we will need a course locator, a ccx coach, a ccx name and a max number of students. 

Assume we will use application-level oAuth.

**Comment by pdpinch** [comment]
This should include a parameter to set the maximum number of student enrollments when the CCX is created. See #122

**Comment by giocalitri** [comment]
> This should include a parameter to set the maximum number of student enrollments when the CCX is created. See #122

Is there going to be only one limit of students for CCX or multiple ones? (Deciding if making an extra field in the CCX model or create an new model)

**Comment by pdpinch** [comment]
I'm not sure if understand the decision you're trying to make. 

Each CCX represents a purchase of a fixed number of seats, so each CCX will need one, and only one, `max_student_enrollments_allowed`.

**Comment by giocalitri** [comment]
There are two big unresolved problems in this issue:

1- The APIs designed in the [proposed document](https://docs.google.com/document/d/1JR2dTDkM23olHFrGeTmYE7VzZrGamAWflCBrdsSMxB8/edit?usp=sharing) do not allow the submission of the CCX course structure
2- Currently there is nothing in the CCX Coach Dashboard that prevents the coach from adding chapter he did not buy

After a discussion with @justinabrahms , I think the solution is the following: 
- CCXCon submits the list of `chapters/sections/subsections` as a list of `locators`. Such list is stored inside the CCX Model in a new field.
- In the dashboard, when we build the structure of the course to present to the Coach, we need to hide everything is not in the list of `locators` (this might be an expensive operation).

**Comment by pdpinch** [comment]
Closed in favor of the upstream PR edx#11166
