### ISSUE TITLE
CCX Connector initial app

### ISSUE THREAD

**Issue by pdpinch** [mitocw/edx-platform#121]
Based on https://docs.google.com/document/d/1K2iRF4BGWZk82Bj7cwEeJ69PpJfHKbVculLx3MsHUss/edit#

**Comment by ShawnMilo** [comment]
I'm unable to find the "course overview" mentioned in the meeting. Is a link available?

I found the [course structure API](http://edx.readthedocs.org/projects/edx-platform-api/en/latest/course_structure/overview.html), but it doesn't have the level of detail necessary, and the [Mobile API](http://edx.readthedocs.org/projects/edx-platform-api/en/latest/mobile/course_info.html), but it doesn't have detailed course information; it's very user-centric.

**Comment by pdpinch** [comment]
Hmm. I was expecting course structure to be more than you needed to get started. What's missing from it?

(Meanwhile, I'm looking for "course overview")

**Comment by ShawnMilo** [comment]
The course structure fields don't have any information about the CCX eligibility, but if all you have in mind for now is simply getting data on all courses, it should be fine.

**Comment by pdpinch** [comment]
I was expecting that we would have to add enable_ccx and ccx_connector to the API resposne -- although I wonder if there's an obvious location for it?

There's a gazillion "advanced settings" on courses. I don't know if any of them are exposed via the API. Maybe that's exactly the question we need to ask edX -- is there an API that exposes advanced settings?

**Comment by pdpinch** [comment]
There was also some discussion of a "Course Metadata" API but I'm not sure if it was ever shipped: https://openedx.atlassian.net/wiki/display/SOL/Open+edX%3A+LMS+Course+Metadata+API

**Comment by pdpinch** [comment]
After some discussion with @Ferdi this should start with the 4 models outlined in the docs and a basic CRUD API. 

pulling course info from the edX APIs is the 2nd step.

**Comment by pdpinch** [comment]
Hey @justinabrahms. Can we call this done once https://github.com/mitodl/ccxcon/pull/7 merges?

**Comment by justinabrahms** [comment]
Yes.

**Comment by justinabrahms** [comment]
Fixed as part of https://github.com/mitodl/ccxcon/pull/7
