### ISSUE TITLE
Limit student enrollments in CCX

### ISSUE THREAD

**Issue by pdpinch** [mitocw/edx-platform#122]
As an instructor, I would like to limit the number of students enrolled in a CCX to avoid having them compete with my MOOC. Also, some CCXs features like the gradebook do not perform well with more than 200 students. 

There is an advanced setting for courses named `max_student_enrollments_allowed` but we don't know how/if it limits enrollments. If it can be use to prevent enrollments over the maximum, we should set the default when the CCX is created, using a field override. 

The limit should default to 200. When we develop an API for creating CCXs #119 `max_student_enrollments_allowed` should be a parameter.

**Comment by giocalitri** [comment]
I'm closing this since the PR has been merged.
