### ISSUE TITLE
When adding a student via "Student List Management" honor the email notification setting

### ISSUE THREAD

**Issue by pdpinch** [mitocw/edx-platform#124]
From Chis Chudzicki:

> In the coach dashboard, only batch enrollment can notify student by email. Is this intentional?

<img width="589" alt="screen shot 2015-10-27 at 10 37 17 am" src="https://cloud.githubusercontent.com/assets/430126/10761224/b7e09adc-7c96-11e5-857b-dfca88172aaf.png">

**Comment by amir-qayyum-khan** [comment]
So you want me to display these checkbox in student list management? So that coach can decide if he need to send a email to student.

Second show auto enrol as disabled check box. because i already made a PR https://github.com/mitocw/edx-platform/pull/117?

**Comment by pdpinch** [comment]
sounds good

**Comment by pdpinch** [comment]
I'll close this once it's released, probably the week of 11/30.
