### ISSUE TITLE
Ability for master course instructor to view CCX as if a student or coach in that CCX

### ISSUE THREAD

**Issue by pdpinch** [mitocw/edx-platform#125]
from Davidson:

> These issues came up while supporting DavidsonNext pilot teachers as they constructed their first CCXs. Base course staff want to know (a) Have teachers started making their courses? Are teachers successfully enrolling students in their CCX? How can view exactly what Coach#2 is viewing?

> Provide the base course staff with:
> Ability for base course instructor to view individual CCX as if a student or coach in that CCX
useful for base course staff to troubleshoot coach issues
perhaps this could be implemented by improving the existing edX feature “View Course as … Specific Student”. Currently, the “View Course as Specific Student” feature does not allow base course staff to masquerade as a CCX coach. (If base course staff masquerades within base course as a student with coach status, coach dashboard does not appear.)

- [ ] #126 Enroll master courses' instructor in CCX as staff
- [ ] Enable "student masquerade" function (should come for free with the above item)
- [ ] Enable CCX Coach dashboard for staff on CCX

**Comment by pdpinch** [comment]
@amir-qayyum-khan are you already working on this?

**Comment by pdpinch** [comment]
@amir-qayyum-khan is the 3rd bullet "Enable CCX Coach dashboard for staff on CCX" part of  edx#10877 ? If not, I'll create a new issue for it.

**Comment by amir-qayyum-khan** [comment]
@pdpinch 
No it is not. But It should be. Do you mind if I add this part in edx#10877 ?

**Comment by pdpinch** [comment]
How would you add this functionality?

I'm starting to change my mind, because is seems unlikely that we'll get 10877 into the next release (to be cut 11am Friday). 

- Peter

**Comment by amir-qayyum-khan** [comment]
IF you think so that we have time on edx#10877 then I can change status to WIP and can add this functionality into it ``` Enable CCX Coach dashboard for staff on CCX``` because edx#10877 is pre-req of this PR, what do you say?

**Comment by amir-qayyum-khan** [comment]
@pdpinch ```Enable CCX Coach dashboard for staff on CCX```
Does this mean instructor/admin as well?

**Comment by pdpinch** [comment]
edx#11787 was finally released on 4/14!
