### ISSUE TITLE
When creating a CCX, enroll the master course's instructors, as staff

### ISSUE THREAD

**Issue by pdpinch** [mitocw/edx-platform#126]
As a (master) course instructor, I'd like to have some visibility into how CCX coaches are using my course.  

As a technical support person, I need to be able to access individual CCXs so I can help CCX coaches.

It would be nice to have course roles "cascade" from the master course to the CCX and be updated whenever the master course is updated. However, I don't know of any way to trigger this update. We may be limited to simply enrolling existing course staff when the CCX is created and having to do updates after the CCX is created by hand. 

Part of #125 
Some similarity to #36 

Presenting a list of CCXs based of the master course is out of scope for this issue.

**Comment by amir-qayyum-khan** [comment]
@pdpinch 

On ccx create we need to add master course instructor:

- As student in ccx
- As staff in ccx course

???

**Comment by pdpinch** [comment]
The story is to add instructors as admin staff. 

I expect that you will need to enroll them as well, in order for them to actually be able to view the course as admin staff.

**Comment by amir-qayyum-khan** [comment]
i am gona start work on it

**Comment by giocalitri** [comment]
@amir-qayyum-khan If you do not mind, could you please create a generic function for this? I need to use it also in the REST API views and I do not want to replicate the code.

**Comment by amir-qayyum-khan** [comment]
sure

**Comment by amir-qayyum-khan** [comment]
@pdpinch 

- A course can have multiple staff members
- Do I need to assign staff roll on new ccx to all staff of master course.
?

**Comment by pdpinch** [comment]
@amir-qayyum-khan Sorry I missed your question from last Monday: 

Yes, all staff of the master course should be assigned to the CCX.

**Comment by amir-qayyum-khan** [comment]
@pdpinch done with that.

**Comment by pdpinch** [comment]
This can be closed when edx#10877 is merged.

**Comment by pdpinch** [comment]
edx#11787 was finally released on 4/14!
