### ISSUE TITLE
When publishing a master course with a ccx_connector, post to the connector

### ISSUE THREAD

**Issue by pdpinch** [mitocw/edx-platform#128]
As a course author, when I set a value for `ccx_connector` in the Advanced Settings, I want information about my course to be published into the CCX connector

To start with, the POST can be made when the setting is changed. Later we may want to make a POST every time a course is published. 

Whenever a course is published and it has a value for `ccx_connector` we should create a POST to the CCX connector endpoint. The post should contain everything necessary to create a new course in the ccx_connector.

**Comment by pdpinch** [comment]
This story follows on #118

**Comment by pdpinch** [comment]
fyi @amir-qayyum-khan 

@ShawnMilo can you update this with the endpoint and the fields necessary?

**Comment by ShawnMilo** [comment]
@pdpinch: So this augments the data at the top of #121, right?

**Comment by pdpinch** [comment]
That's correct.

**Comment by pdpinch** [comment]
Do we need to post all the course info and course structure, or can we rely on the connector calling back to edX's course structure API.

**Comment by justinabrahms** [comment]
It'd be nice from a testing perspective if we had a bunch of stuff like:

```
        {
          "title": "Quantum Mechanics",
          "author": "Bilbo Baggins",
          "overview": "Quarks and photons and lots of other stuff.",
          "description": "test description",
          "video_url": "https://www.youtube.com/watch?v=ROor6_NGIWU",
          "modules": [
            {
              "title": "Gandalf comes to see Bilbo",
              "subchapters": ["test", "titles", "go", "here"]
          ]
        }
```

Then we minimize the dependency upon edx.

**Comment by pdpinch** [comment]
I'm not sure what you mean. Are you looking for sample data? If so, how much is a bunch?

And you're looking for JSON that would be used for a POST for creating a course in the ccx_connector, yes?

**Comment by justinabrahms** [comment]
Sorry, no. I typed that during the meeting and didn't properly proofread. That is what I'd really like to get as a payload to the create endpoint. Then we could make the course and it's modules in one pass, which would be nice.

**Comment by pdpinch** [comment]
Needs to authenticate to CCX connector.

**Comment by giocalitri** [comment]
according to [the ccxcon apiary description](http://docs.ccxcon.apiary.io/#reference/ccx-modules/module-membership/create-a-new-course), ex has to post to the url
```
http://teachers.odl.mit.edu/api/v1/coursexs/
```
with a body like
```
{
  "title": "Introductory Physics: Classical Mechanics",
  "author_name": "David E. Pritchard",
  "edx_instance": "https://edx.org",
  "overview": "This is the course overview.",
  "description": "This is a college level Introductory Newtonian Mechanics",
  "video_url": "https://www.youtube.com/watch?v=ROor6_NGIWU",
  "instructors": [
    "2d133482b3214a119f55c3060d882ceb"
  ]
}
```

`title` I suppose is the edx `display_name`, `instructors` is a list of anonymous IDs, `edx_instance` is the base url of the current instance, but what is the rest?

**Comment by pdpinch** [comment]
title => course.display_name
author_name => None (this doesn't exist in edX, as such)
edx_instance => pull from SETTINGS
overview => I think this is course.description. It's an HTML blob
description => course.short_description, I believe
video_url => this should have been a course_image URL
Instructors has been discussed elsewhere

[ ] add an issue to CCXCon post course_images to S3 so we're not calling on edX (and turn on versioning on S3! and MFA too)

**Comment by amir-qayyum-khan** [comment]
@pdpinch @giocalitri Added post call to ccx_connector
https://github.com/mitocw/edx-platform/pull/123/files#diff-461736c08928fe2e89e3776a671fc5b1R10

Can you guys suggest me how to test it?

**Comment by pdpinch** [comment]
opened at edx/edx-platform#10931
