### ISSUE TITLE
Don't allow users to self-register for CCX

### ISSUE THREAD

**Issue by pdpinch** [mitocw/edx-platform#138]
As an instructor, I don't want CCXs made from my course competing with the original MOOC. I expect enrollment to be by invitation only. 

I can think of two (maybe three) ways to do this:

When the CCX is created, we can override the `enrollment_end` date to be a date in the past
We can disable the enrollment buttons on the course info page and on the courseware template when the user is inside a CCX
There may be a course advanced setting that prevents enrollments globally.

**Comment by amir-qayyum-khan** [comment]
@pdpinch 

This is another way to solve this problem. Which is hide registration process from student in case he want to self register ccx (Here is demonstration)[https://github.com/mitocw/edx-platform/pull/164]

**Comment by pdpinch** [comment]
The screenshots look good, but I'm confused why the code goes into the about_page function -- does that get called even when an unenrolled user tries to access other pages in the course?

**Comment by amir-qayyum-khan** [comment]
@pdpinch This page is called when an unenrolled student tries to access course by any tab courseware, course info , progress, wiki etc

**Note this is not applicable if student is admin/staff of the course **

**Comment by pdpinch** [comment]
Hmm. I can still reach the info page, which give me a link to sign up. When I click that link I get redirected to my dashboard. 

On edX configurations, it seems to direct unenrolled users to the info page instead of the about page. Can we add the same check to the info page?

**Comment by amir-qayyum-khan** [comment]
sure, let me add

**Comment by amir-qayyum-khan** [comment]
Done @pdpinch , please review
