### ISSUE TITLE
"View this course as: Student" doesn't work in CCX

### ISSUE THREAD

**Issue by pdpinch** [mitocw/edx-platform#155]
As the staff member or instructor of a master course, I would like to be able to view a CCX as a CCX student would see it. Using the "View this course as" widget does not display the CCX overrides when set to "Student," although it will honor the overrides when set to a Specific student who is enrolled in the CCX.

**Comment by amir-qayyum-khan** [comment]
Fixed via https://github.com/edx/edx-platform/pull/10877

**Comment by pdpinch** [comment]
ed#10877 has been merged. We can close this when it's released.

**Comment by pdpinch** [comment]
edx#11787 was finally released on 4/14!
