### ISSUE TITLE
Account for course staff when checking max enrollments

### ISSUE THREAD

**Issue by pdpinch** [mitocw/edx-platform#159]
When a student is enrolled in a CCX, we check to see that we haven't gone over the MAX_STUDENT_ENROLLMENTS_ALLOWED. Since the coach and the master course staff use enrollments, we need to exclude them from the count. 

Check to see how edX uses this course setting now. Are we duplicating existing code?

**Comment by pdpinch** [comment]
@giocalitri wrote the code for checking the maximum enrollments in the CCX app

**Comment by amir-qayyum-khan** [comment]
@pdpinch 
- I was looking into enrollment process for instructor https://github.com/edx/edx-platform/blob/master/lms/djangoapps/instructor/views/api.py#L319
- Found no use of ``max_student_enrollments_allowed``
- CCX code seems ok, I dont think of any specific duplication.
- I made some addition to exclude staff from course limit count https://github.com/mitocw/edx-platform/pull/203

**Comment by amir-qayyum-khan** [comment]
PR merged upstream https://github.com/edx/edx-platform/pull/11947
