### ISSUE TITLE
add course modules to create ccx api

### ISSUE THREAD

**Issue by pdpinch** [mitocw/edx-platform#170]
As a coach, I'd like to purchase individual modules for my CCX in order to save money. I expect that the module that I purchase (and no others) will be available in the schedule tab of my coaches dashboard. 

The API for creating CCXs needs to be modified so that a list of purchased modules (location keys) can be passed with the request to create or update a CCX.

**Comment by giocalitri** [comment]
There is no easy way to store the locator strings in the CCX Module.

Possible solutions are:
a. json-stringify the list and put it in a text field
b. create a reference to a the place where the master course moduleds are stored

I am going to investigate the option n.2, given that I feel like it is what edx will like the most.

**Comment by giocalitri** [comment]
after seeing that in the `CourseStructure` model there is a a compressed text field to store json, I will proceed with the solution a.

**Comment by pdpinch** [comment]
edX#11356

**Comment by pdpinch** [comment]
This can be closed once edx#11356 is released

**Comment by pdpinch** [comment]
edx#11356 was released on or about 3/2
