### ISSUE TITLE
edX DevOps tasks

### ISSUE THREAD

**Issue by pdpinch** [mitocw/edx-platform#171]
The edX DevOps team will need to do a few things for a complete CCX deployment. Presumably, they will have to do these things on stage.edge.org, edge.edx.org and edx.org

From past experience, we should give them as much advance warning as possible, probably through Dave (since we can't create JIRA tickets in the DevOps team). 

This issue should be filled out with a checklist of to do items.

**Comment by pdpinch** [comment]
@justinabrahms since you brought it up, can you fill in what you had in mind? 

Will any of these things be necessary for verifying and deploying individual edX PRs? If so, please not the PR number. 

@giocalitri FYI

**Comment by justinabrahms** [comment]
They'll need a ccxcon user, ccxcon model object (see the edx -> ccxcon post PR), to generate an oauth client for us (tied to the previous user) and an oauth grant (also tied to previous user and client). We'll need the values from that (grant token, oauth client tokens).

I think that might be it.

**Comment by giocalitri** [comment]
Just a clarification: to add a ccxcon model object, the edX DevOps people will need some info about the CCXConnector that we will provide; instead for the rest they do not need anything from us.

**Comment by pdpinch** [comment]
Is this info necessary for testing the PRs as well? Is that somewhere in the PR description?

**Comment by giocalitri** [comment]
which PR?

**Comment by giocalitri** [comment]
It depends how we want to test the PRs.
But there are enough info in the PR descriptions to test them on local instances

**Comment by pdpinch** [comment]
Add these to the PRs in the question & then tag e0d

**Comment by pdpinch** [comment]
This is done.
