### ISSUE TITLE
Bug: when creating a CCX via REST API, the coach can't access the coach dashboard

### ISSUE THREAD

**Issue by pdpinch** [mitocw/edx-platform#175]
First guess: the coach role isn't being created properly.

**Comment by giocalitri** [comment]
I think I found the source of the problem: the dashboard simply does not support multiple CCX on the same master course for the same coach. I am able to replicate the problem.

**Comment by pwilkins** [comment]
This was a limitation of the original CCX release.  For MVP, it wasn't considered necessary for a coach to have more than one CCX on a given master course.

**Comment by amir-qayyum-khan** [comment]
@pwilkins CCX architecture supports/allows multiple instance (edx#master). This functionality was suppress in code. Just need to update few check, fixed this issue in #182.

**Comment by pwilkins** [comment]
@amir-qayyum-khan Thank you for the clarification.  I knew that the feature wasn't available to users, I didn't know that the architecture supported it from the outset.

**Comment by pdpinch** [comment]
@giocalitri how did you want to handle this? Should it be merged into your https://github.com/edx/edx-platform/pull/11166 PR ?

**Comment by giocalitri** [comment]
@pdpinch I do not think it's necessary: it's pretty unlikely that we will create multiple CCX for the same Coach through the APIs before this is merged

**Comment by pdpinch** [comment]
So we should open it upstream after edx#11166 is merged?

**Comment by giocalitri** [comment]
I think it is independent

**Comment by pdpinch** [comment]
This can be closed once #11545 is released to edx.org and edge.edx.org (expected Wednesday 3/2)
