### ISSUE TITLE
Update MITx configuration to run against Dogwood

### ISSUE THREAD

**Issue by pdpinch** [mitocw/edx-platform#179]
there are backwards incompatible things, such as

- [ ] upgrading from django 1.4 to 1.8

**Comment by pdpinch** [comment]
@blarghmatey is this still relevant?

**Comment by blarghmatey** [comment]
I think this is covered by the work we are doing right now.


Regards,

Tobias Macey

Senior DevOps Engineer

MIT Office of Digital Learning

http://odl.mit.edu

On Monday, July 18, 2016 8:18:16 AM EDT Peter Pinch wrote:

@blarghmatey<https://github.com/blarghmatey> is this still relevant?

**Comment by blarghmatey** [comment]
Closing this as we currently have a production ready Dogwood stack and associated configuration management/provisioning capabilities.
