### ISSUE TITLE
When a CCXConnector URL is added to a course, prevent creation of new CCX in lms

### ISSUE THREAD

**Issue by pdpinch** [mitocw/edx-platform#189]
As an instructor, when I set a URL for the CCXConnector advanced setting, I expect the creation of CCXs to be managed by another web site (presumably for a fee). Coaches should no longer be allowed to create their own CCXs via the coach dashboard. 

It's OK to just return an error at this time, when a coach tried to create a CCX on course with a CCXCon setting.

**Comment by amir-qayyum-khan** [comment]
@pdpinch @giocalitri 

- So we will still show the create CCX form?
- When coach presses create ccx button then I will check (via javascript) at that point if CCXConnector is set then I will show him error message 
 - "Please use  CCXConnector application to create CCX."
- if CCXConnector url is not set then coach can create CCX via form?
- This will be same for multiple instance of ccx?

**Comment by pdpinch** [comment]
To keep things as simple to implement as possible, I was thinking that:

- [ ] We still show the coach the create CCX Form
- [ ] When the form is submitted:
  - [ ] If the CCXConnector URL is NOT set, a CCX is created as normal
  - [ ] if the CCXConnector URL IS set, an error is returned. If possible, the error message should include the setting for CCXCon URL in the course's advanced settings
- [ ] The behavior is the same no matter how many CCXs have been created in the past.
