### ISSUE TITLE
RP release

### ISSUE THREAD

**Issue by pdpinch** [mitocw/edx-platform#191]
With a short list of cherry-picks, to be identified.

Includes the fix to the Save Race condition bug, gradebook export (in progress) and possibly some PRs from Jolyon.

**Comment by pdpinch** [comment]
The intended release was superseded. This release won't happen this sprint (Valentine's Day)

**Comment by bdero** [comment]
@pdpinch I did a release of Staging and RP with a bunch of configuration changes in RP, are we accounting for that in this sprint?

**Comment by bdero** [comment]
This was the release PR, which only had 1 simple change on edx-platform: https://github.com/mitocw/edx-platform/pull/186

**Comment by pdpinch** [comment]
You're right. We should close this and just open another one for next sprint.
