### ISSUE TITLE
XBlockSaveError 

### ISSUE THREAD

**Issue by pdpinch** [mitocw/edx-platform#200]
Hidden amongst the large number of pickle errors (see #199) we are seeing this semester is a much smaller number of `XBlockSaveError` 

We haven't heard anything from users, but these seem more likely to me to cause lasting issues. I'll post some sample stack traces after I make sure they don't reveal any student data.

**Comment by pdpinch** [comment]
In October there was a PR to the XBlock repo which apparently improves the error logging around this exception. 

https://github.com/edx/XBlock/pull/323

I would guess that this change would be part of Dogwood, but I don't know for sure.

**Comment by pdpinch** [comment]
It appears to be the case that these are primarily (only) related to saving state for video.

**Comment by pdpinch** [comment]
On further investigation, the commit at https://github.com/edx/XBlock/pull/323 just improves the logging. It doesn't address the issue. 

As far as I can tell, the issue still exists in edX as of eucalyptus.

**Comment by blarghmatey** [comment]
Is this still an issue or can we close it?
