### ISSUE TITLE
Add staff and instructors users as staff of a CCX created via REST APIs

### ISSUE THREAD

**Issue by giocalitri** [mitocw/edx-platform#205]
comment https://github.com/edx/edx-platform/pull/10877#issuecomment-173222178

**Comment by pdpinch** [comment]
Is this now being solved by #208?

**Comment by pdpinch** [comment]
This can be closed after edx/edx-platform#11787 is released, presumably around 4/6.

**Comment by amir-qayyum-khan** [comment]
merged via https://github.com/edx/edx-platform/pull/11787

**Comment by pdpinch** [comment]
Did you confirm this was working on stage.edx.org ?

**Comment by amir-qayyum-khan** [comment]
yes @pdpinch
