### ISSUE TITLE
Write script to detect all courses with duplicate roles (caused by a race condition)

### ISSUE THREAD

**Issue by bdero** [mitocw/edx-platform#214]
We get these emails a lot and it often interrupts ed-techs and course devs.

**Comment by pdpinch** [comment]
@bdero can Amir work on this, or would he be blocked by not having access to the bad data in question?

**Comment by bdero** [comment]
I think the next time we see these errors, I will just write this as I fix the issue. It's a two line change from what I usually end up typing. @pdpinch

**Comment by pdpinch** [comment]
It's possible this was fixed in dogwood. If we don't have any incidents by October, we can close this.

**Comment by pdpinch** [comment]
This cropped up again in ficus. See https://odl.zendesk.com/agent/tickets/10761

**Comment by pdpinch** [comment]
Closed in favor of https://github.com/mitodl/salt-ops/issues/407
