### ISSUE TITLE
OAUTH grant gets created even if there is an existing one

### ISSUE THREAD

**Issue by giocalitri** [mitocw/edx-platform#217]
Using EDX as OAUTH provider works, but a new grant is created each time a login is performed instead of looking for an existing one, even if the user and the scope are the same.

The server should see if a grant has been issued and if it is still valid and only if if cannot find any should create a new one.

<img width="1393" alt="screen shot 2016-03-08 at 11 43 03 am" src="https://cloud.githubusercontent.com/assets/1005204/13608483/f92c7034-e522-11e5-85e1-edf44f6db075.png">

**Comment by giocalitri** [comment]
I started to investigate looking at the [django-oauth2-provider](https://github.com/edx/django-oauth2-provider) and looked at this function https://github.com/edx/django-oauth2-provider/blob/edx/provider/oauth2/views.py#L68 but I am unable to understand what triggers the creation of a Grant and authorization code. 

It seems that this view https://github.com/edx/edx-oauth2-provider/blob/master/edx_oauth2_provider/views.py#L26 is called first and that probably the magic happens in the `edx-oauth2-provider` library instead.

We should investigate where the search for an existing access token happens and where it creates the grant.

**Comment by giocalitri** [comment]
From a discussion with Justin on the Teacher's Portal Chat
```
diff --git a/backends/edxorg.py b/backends/edxorg.py
index d8c423b..dab76d6 100644
--- a/backends/edxorg.py
+++ b/backends/edxorg.py
@@ -9,17 +9,17 @@ from social.backends.oauth import BaseOAuth2
 class EdxOrgOAuth2(BaseOAuth2):
     """
-    EDX.org OAuth2 authentication backend
+    EDX.org OAuth2 authentication backend (newer one)
     """
     name = 'edxorg'
     ID_KEY = 'edx_id'
     REQUEST_TOKEN_URL = None
     EDXORG_BASE_URL = settings.EDXORG_BASE_URL
-    AUTHORIZATION_URL = urljoin(EDXORG_BASE_URL, '/oauth2/authorize/')
-    ACCESS_TOKEN_URL = urljoin(EDXORG_BASE_URL, '/oauth2/access_token/')
+    AUTHORIZATION_URL = urljoin(EDXORG_BASE_URL, '/_o/authorize/')
+    ACCESS_TOKEN_URL = urljoin(EDXORG_BASE_URL, '/_o/token/')
     ACCESS_TOKEN_METHOD = 'POST'
     REDIRECT_STATE = False
-    DEFAULT_SCOPE = ['email']
+    #DEFAULT_SCOPE = ['email']
     def user_data(self, access_token, *args, **kwargs):
         """
```
That will create clients on edx's new oauth provider which currently lacks acceptable templates and doesn't solve the underlying "authorization code" problem where we have to continually re-ask for permission.

**Comment by pdpinch** [comment]
@giocalitri any news on this?

**Comment by giocalitri** [comment]
Nothing from edX people. I did not work on this yet

**Comment by giocalitri** [comment]
The micromaster PR https://github.com/mitodl/micromasters/pull/299 takes care of this with this setting:
https://github.com/mitodl/micromasters/pull/299/files#diff-1d638380b48b7582683d975a864c8db0R169
