### ISSUE TITLE
discovery: how can we get current grades from edX?

### ISSUE THREAD

**Issue by pdpinch** [mitocw/edx-platform#219]
Part of mitodl/micromasters#58

Take a look at edX's plans for grades persistence and events: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/edx-code/JNKYj3ACGus/6N_iNFsgBwAJ

How can we leverage this in MicroMasters? Should we pursue a REST API to access persistent grades? Or tap into the events?

**Comment by pdpinch** [comment]
edX has started working on a separate django app for grades. See https://github.com/edx/edx-platform/pull/13053 and [TNL-5008](https://openedx.atlassian.net/browse/TNL-5008), part of the [robustifying grades epic](https://openedx.atlassian.net/browse/TNL-4546). It looks like their goal is to eventually move towards an IDA.

FYI @Ferdi @giocalitri

**Comment by giocalitri** [comment]
The current view in edX to see the current grade is in 
`lms.djangoapps.courseware.views.views._progress`

The information we are interested in is the output of the call 
`grade_summary = course_grades.summary(student, course, course_structure=course_structure)`

that looks like

```
{'grade': None,
 'grade_breakdown': [{'category': u'Homework',
                      'detail': u'Homework = 3.41% of a possible 75.00%',
                      'percent': 0.03409090909090909},
                     {'category': u'Exam',
                      'detail': u'Exam = 0.00% of a possible 25.00%',
                      'percent': 0.0}],
 'percent': 0.03,
 'section_breakdown': [{'category': u'Homework',
                        'detail': u'Homework 1 - Homework - Question Styles - 9% (1/11)',
                        'label': u'Ex 01',
                        'percent': 0.09090909090909091},
                       {'category': u'Homework',
                        'detail': u'Homework 2 - Homework - Labs and Demos - 0% (0/1)',
                        'label': u'Ex 02',
                        'percent': 0.0},
                       {'category': u'Homework',
                        'detail': u'Homework 3 Unreleased - 0% (?/?)',
                        'label': u'Ex 03',
                        'mark': {'detail': u'The lowest 1 Homework scores are dropped.'},
                        'percent': 0},
                       {'category': u'Homework',
                        'detail': u'Homework Average = 5%',
                        'label': u'Ex Avg',
                        'percent': 0.045454545454545456,
                        'prominent': True},
                       {'category': u'Exam',
                        'detail': u'Exam = 0%',
                        'label': u'Exam',
                        'percent': 0.0,
                        'prominent': True}],
 'totaled_scores': {u'Exam': [Score(earned=0.0, possible=1.0, graded=True, section=u'edX Exams', module_id=None)],
                    u'Homework': [Score(earned=1.0, possible=11.0, graded=True, section=u'Homework - Question Styles', module_id=None),
                                  Score(earned=0.0, possible=1.0, graded=True, section=u'Homework - Labs and Demos', module_id=None)]}}
```

and in particular the number we need is `percent` in this JSON blob.

**Comment by giocalitri** [comment]
I think that what we should do is detach the code in `_progress` that takes care of extracting the informations and leave only the the template rendering. In this way we can expose the bare data.
