### ISSUE TITLE
discovery: research how student final grades are materialized

### ISSUE THREAD

**Issue by pdpinch** [mitocw/edx-platform#223]
related to micromasters

We will need to write an API. 

We can start the progress by opening a blank PR and discussing (either in GithHub or on the related PR)

**Comment by giocalitri** [comment]
The students final grades are located in the [GeneratedCertificate](https://github.com/edx/edx-platform/blob/master/lms/djangoapps/certificates/models.py#L204) model.

The generation of a certificate is made through [api.generate_user_certificates](https://github.com/edx/edx-platform/blob/master/lms/djangoapps/certificates/api.py#L94).

It seems that a certificate is generated also for users that have not passed a course, but the status of the certificate is set to `notpassing` ([see models. certificate_status_for_student](https://github.com/edx/edx-platform/blob/master/lms/djangoapps/certificates/models.py#L440)).

A quick way to get the certificates for a student is [api. get_certificates_for_user](https://github.com/edx/edx-platform/blob/master/lms/djangoapps/certificates/api.py#L46) that seems to return everything we need:
```
        {
            "username": "bob",
            "course_key": "edX/DemoX/Demo_Course",
            "type": "verified",
            "status": "downloadable",
            "download_url": "http://www.example.com/cert.pdf",
            "grade": "0.98",
            "created": 2015-07-31T00:00:00Z,
            "modified": 2015-07-31T00:00:00Z
        }
```

Something missing is an api to retrieve a certificate for a given user and course id, but it is only an additional filter on the `GeneratedCertificate` model.

Something to take in account might be the [CertificateInvalidation](https://github.com/edx/edx-platform/blob/master/lms/djangoapps/certificates/models.py#L378) table. The question relevant for us is: if a user has an invalidated certificate, has he completed the course or not?
