### ISSUE TITLE
De-normalized grades don't work with pre-computed grades

### ISSUE THREAD

**Issue by pdpinch** [mitocw/edx-platform#226]
Steps to reproduce:
1. Go to the legacy dashboard of a course that has pre-computed grades, e.g. https://prod-staging.mitx.mit.edu/courses/DevOps/0.001/2015_Summer/legacy_instructor_dash
2. Check the box to use pre-computed grades
3. Uncheck the box to normalize grades. 
4. Enter an assignment name, e.g. "HW 01"
5. Click "Display Grades for Assignment"

Results:

<img width="630" alt="not normalized and pre-computed" src="https://cloud.githubusercontent.com/assets/430126/13778401/ebed5ce4-ea8b-11e5-8916-d03352e90e7a.png">

Expected Results:

It should return the same table as when pre-computed is not checked, i.e.

<img width="374" alt="not normalized and not pre-computed png" src="https://cloud.githubusercontent.com/assets/430126/13778431/1f1295d0-ea8c-11e5-9770-de44b278ce11.png">

**Comment by amir-qayyum-khan** [comment]
#### List of assignments
![screen shot 2016-03-15 at 6 26 04 pm](https://cloud.githubusercontent.com/assets/10431250/13779202/abbfefec-eadb-11e5-8261-4d2104ad247d.png)

#### Non normalize grades
![screen shot 2016-03-15 at 6 26 40 pm](https://cloud.githubusercontent.com/assets/10431250/13779201/abbe3b02-eadb-11e5-9f8b-0452e6792e30.png)
![screen shot 2016-03-15 at 6 27 01 pm](https://cloud.githubusercontent.com/assets/10431250/13779204/abc3e660-eadb-11e5-921d-e8a229386da2.png)

#### Normalize grades
![screen shot 2016-03-15 at 6 27 14 pm](https://cloud.githubusercontent.com/assets/10431250/13779205/abc5da74-eadb-11e5-8de5-8fbbe201a178.png)
![screen shot 2016-03-15 at 6 27 26 pm](https://cloud.githubusercontent.com/assets/10431250/13779203/abc25692-eadb-11e5-8eea-0c32b01793cf.png)

**Comment by pdpinch** [comment]
We should start by looking at the pre-computed grades management command to see if it has tests.

**Comment by pdpinch** [comment]
For reference, you can execute the management command with:

```
/edx/bin/python.edxapp /edx/app/edxapp/edx-platform/manage.py lms --settings=aws compute_grades DevOps/0.001/2015_Summer
```

`--setting` flag varies depending on environment (e.g. devstack should leave it out), and the last param is the course key

**Comment by amir-qayyum-khan** [comment]
@pdpinch @bdero unable to produce this issue on **``MIT: 8.S05 Quantum Physics II``**.

![screen shot 2016-03-30 at 2 38 54 pm](https://cloud.githubusercontent.com/assets/10431250/14138180/386f748a-f685-11e5-9893-b2a2406986a7.png)

![screen shot 2016-03-30 at 2 38 42 pm](https://cloud.githubusercontent.com/assets/10431250/14138192/40d308c6-f685-11e5-8ff7-de75f3e724dd.png)

**Comment by blarghmatey** [comment]
@pdpinch I'm assuming that we can close this since there are no longer pre-computed grades?

**Comment by pdpinch** [comment]
Good point. 

There's still some call for "de-normalized" grades, which we had to revert, but this issue isn't relevant any more.
