### ISSUE TITLE
Certificates API needs new Authentication and Authorization to work with new OAuth library

### ISSUE THREAD

**Issue by pdpinch** [mitocw/edx-platform#239]
In their implementation of OAuth, edX wrote new authentication and authorization code. We need to port this to the certificates API in order for it work with the new OAuth library. 

@giocalitri already has a WIP PR for this: https://github.com/mitocw/edx-platform/pull/238

**Comment by pdpinch** [comment]
The description should be updated with the actual name of the OAuth library (instead of "new"), which I don't know off the top of my head.

**Comment by giocalitri** [comment]
The new library is called `Django OAuth Toolkit` but the code is older that that library and works with both the old library and the new one.
I updated the description to avoid to reference a specific version.

**Comment by giocalitri** [comment]
Closing this: https://github.com/edx/edx-platform/pull/12435 has been merged
