### ISSUE TITLE
EDX List scopes for Micromaster app

### ISSUE THREAD

**Issue by giocalitri** [mitocw/edx-platform#241]
We need to define the list of endpoints and HTTP methods (GET, POST, etc) MicroMasters hits.

**Comment by giocalitri** [comment]
the list of endpoints currently used by MicroMasters:

- `GET /api/user/v1/accounts/<username>`
- `GET /api/mobile/v0.5/my_user_info`
- `GET /api/enrollment/v1/enrollment`
- `GET /api/certificates/v0/certificates/<username>/courses/<course_id>/` 

informal list we want to use in the future:
- `GET /api/certificates/v0/certificates/<username>/` as soon as we implement it
- (probably) `POST` endpoint to enroll a student
- (probably) `POST` endpoint to upgrade students to verified enrollment
- `GET` endpoint to pull current grade for a student

**Comment by pdpinch** [comment]
Rather than POSTing to upgrade students to verified enrollment, I think we want to POST to add a verified enrollment to the learner's basket.

**Comment by giocalitri** [comment]
I have not a clear idea of how this works actually: I will change the comment

**Comment by giocalitri** [comment]
updated

**Comment by efagin** [comment]
Thanks. That all makes sense.

My understanding, just to make sure I get the point: the rough sketch of scopes you'd need are
* `read` for `credentials`, which would likely include the `certificates` and `credentials` endpoints
* `read` **and** `write` for `enrollments`
* `read` for `profile`, which would include the `accounts` and `my_user_info` endpoints
* (someday) `read` for `grades`

where `read` and `write` would map to the typical HTTP verbs for those things. We haven't actually written down a spec yet but does that all make sense? If so then we're at least on the right track.

**Comment by giocalitri** [comment]
@efagin 

1. yes, if we assume we will use the `credentials` endpoint in the future and not the newly created certificates endpoint.
2. yes, assuming `write` does not mean only `POST`
3. here I am a bit lost
4. yes

**Comment by efagin** [comment]
@giocalitri 

1. yes, that's what I mean
2. yes, by "typical HTTP verbs" I mean `POST`, `PUT`, `PATCH`, maybe also `DELETE` (though that could be a separate scope entirely)
3. I just meant that the concept of a `profile`, to me, includes the username (which you're getting from `my_user_info`) and the user's account/profile information (which you're getting from `accounts`). Does that make more sense or are you still lost? Perhaps I'm missing your original point.
4. cool

**Comment by efagin** [comment]
oh and 2a. verbs for `read` could include `GET`, `HEAD`, and `OPTIONS`, just to finish that thought.

**Comment by giocalitri** [comment]
About the 3.:
I think I understood what you mean.

Now I am wondering if there is a plan (even long term) to unify the two endpoints.

**Comment by efagin** [comment]
Well long term, my goal is to start using JSON web tokens (JWTs) instead of opaque OAuth access tokens, and those JWTs would have basic information like username (so you wouldn't need `my_user_info` any more, which is a win for everybody). We've already started experimenting with this - our OAuth2 provider can issue JWTs (`token_type=jwt`) but most endpoints do not yet support JWT as the Authorization header value.

That said, I wonder if in the interim you just requested a JWT instead of asking my_user_info for the username? It would be a throwaway value and you'd still need to request an access token today, but A. you're now using only v1+ endpoints and B. JWTs will replace access tokens eventually. Just a thought, this one's still half-baked at best.

**Comment by giocalitri** [comment]
Ok, got it.

**Comment by giocalitri** [comment]
I think the scopes for the MicroMasters app have been clarified. I will close this story: we can re open it in case something was not covered.
