### ISSUE TITLE
EDX List scopes for MIT apps

### ISSUE THREAD

**Issue by giocalitri** [mitocw/edx-platform#242]
We need to define the list of endpoints and HTTP methods (GET, POST, etc) MIT apps hit.
#241 Takes care of MicroMasters, so this should take care of the rest

**Comment by pdpinch** [comment]
Trying to use the nomenclature of https://github.com/mitocw/edx-platform/issues/241#issuecomment-218885681, we will need:

`read` for courses (discovery API, already functioning AFAIK)
`read` and `write` for `staff` (no API for this yet, but we'd like to be able to automate adding staff to courses, especially coaches)
`read` and `write` for `ccx` (this is already implemented, with the scope being controlled by staff status)
`read` and course export and `write` for course import

**Comment by pdpinch** [comment]
@giocalitri anything to add above?

**Comment by pdpinch** [comment]
I think this is moot now.
