### ISSUE TITLE
User can access coach dashboard via link even if enable_ccx flag is set false

### ISSUE THREAD

**Issue by amir-qayyum-khan** [mitocw/edx-platform#245]
User can access coach dashboard via link even if CCX is not enabled for the course (in the Advanced Settings), anyone can still access the ccx_coach dashboard endpoint .

**Comment by pdpinch** [comment]
We could also use an estimate for this one as well

**Comment by amir-qayyum-khan** [comment]
@pdpinch made PR https://github.com/mitocw/edx-platform/pull/247
