### ISSUE TITLE
Sever should handle ccx coach dashboard url with invalid ccx id

### ISSUE THREAD

**Issue by amir-qayyum-khan** [mitocw/edx-platform#246]
If the dashboard is accessed by a staff user, with a (non­existent) invalid CCX ID specified, the server returns a 500 error.

**Comment by pdpinch** [comment]
Please add an estimate to this, when you get a chance.

**Comment by amir-qayyum-khan** [comment]
I am done with that creating PR in 30 sec

**Comment by amir-qayyum-khan** [comment]
Made PR https://github.com/mitocw/edx-platform/pull/247

**Comment by amir-qayyum-khan** [comment]
fixed via https://github.com/edx/edx-platform/pull/12889
