### ISSUE TITLE
Write proposal for current grades REST API

### ISSUE THREAD

**Issue by pdpinch** [mitocw/edx-platform#258]
For more information, see #219 and mitodl/micromasters#761

This would be a read-only v0 API for fetching the current grade as displayed on the edX Progress page. If there is a way to easily calculate "progress" as a percentage that should be included as well. 

The proposal should be posted to edx-code and reviewed by Dave, Eddie and someone from Nimisha's team.

**Comment by pdpinch** [comment]
@giocalitri this is done, right? What's the PR number?

**Comment by giocalitri** [comment]
This one

https://github.com/edx/edx-platform/pull/13157

Sent by my iDevice. May be rife with typos or poor judgment.

On Aug 9, 2016, at 8:48 AM, Peter Pinch <notifications@github.com<mailto:notifications@github.com>> wrote:


@giocalitri<https://github.com/giocalitri> this is done, right? What's the PR number?
