### ISSUE TITLE
RST2EDX

### ISSUE THREAD

**Issue by laszewsk** [mitocw/edx-platform#260]
I am not sure where to post this, but we are looking for a trivial conversion from RST into edx. What we want to use is not latex2edx, but actually rst.

We do not need fancy things just dealing with the sections, subsections and horizontal sections.

Do you have such a tool, and if not could it be made so the community could use it

**Comment by pdpinch** [comment]
Sorry, I'm not aware of any tool that does this. It looks like you've already posted on the edX code list, which is my best recommendation.
