### ISSUE TITLE
Allow Coaches to Rename their CCX After Initial Creation

### ISSUE THREAD

**Issue by pdpinch** [mitocw/edx-platform#32]
via Chris Chudzicki:

> Allow Coaches to Rename their CCX After Initial Creation
Clearly coaches should not change the course name very often, but typos do occur. Also, teachers may want to retroactively standardize name formats, e.g., by adding their name (“Mr. Jones”) after the main title.

> Possible implementation: Change the CCX Dashbaord “Grading Policy” panel to “Advanced Settings” and include in there?

This may be easier to address as part of the ui for #34

**Comment by amir-qayyum-khan** [comment]
@pdpinch

Should we create new tab for this setting? Or we  can use existing tab like "student admin" for ccx name update

or 

We can add ccx name under heading "CCX Coach Dashboard" and put pencil icon at the end. On click name/pencil  will open it in edit mode and pencil button will be change into save.
On use press save on enter key the new name will be save.

**Comment by pdpinch** [comment]
Sorry, this isn't ready to be worked on yet.

**Comment by amir-qayyum-khan** [comment]
okay.

**Comment by pdpinch** [comment]
Blocked for similar reasons to #34 although there may be a UI option that isn't dependent on #34

**Comment by amir-qayyum-khan** [comment]
fixed via https://github.com/mitocw/edx-platform/pull/163
