### ISSUE TITLE
Discovery: what would happen if we gave coaches instructor-level access to their CCX?

### ISSUE THREAD

**Issue by pdpinch** [mitocw/edx-platform#35]
Questions:

- [x] Can this be done with existing access controls?
- [x] Does this give the coach any ability to access studio & edit content in the CCX?
- [ ] What other instructor dashboard features could be enabled, or broken?
- [x] Would this allow the coach to use the student masquerade feature?

**Comment by pwilkins** [comment]
Enabling this feature would remove one of the original justifications for CCX.  This is less a development challenge than a policy decision.

**Comment by pdpinch** [comment]
The justification that we've typically given, is that we don't want to allow CCX coaches to edit the course materials or create new content. Does giving coaches instructor-level access to their CCX allow editing, i.e. can you edit a CCX via studio?

Are there other privileges that come with instructor level access of a CCX that we are wary of? We should do a quick survey of the instructor dashboard.

**Comment by pwilkins** [comment]
OK, your issue statement didn't explicitly say that your Instructor privileges only applied to the LMS, and not the CMS.  Now I understand what you're proposing.

**Comment by pdpinch** [comment]
Testing on sandbox2o, giving my CCX instructor access allows him to *view* the CCX in studio, but when I tried to add a new section, Studio returned a 403 error.

**Comment by pdpinch** [comment]
We attempted this as part of #36 and found that it enabled the student masquerade feature, but it also enabled the instructor dashboard, as if the coach were a course staff member. This was a) too much permission and b) confusing b/c there were two dashboards on the CCX.

**Comment by pdpinch** [comment]
Still need to inventory instructor dash features that work and which ones are broken.

**Comment by pdpinch** [comment]
In discussing with Ferdi, we want a unified UX, so any useful staff features from the instructor dashboard need to be added to the Coach dashboard.
