### ISSUE TITLE
When creating a CCX, automatically enroll the coach

### ISSUE THREAD

**Issue by pdpinch** [mitocw/edx-platform#36]
As a CCX coach, I expect to see my CCXs in my dashboard and I expect to be able to see my CCX courseware without manually enrolling. 

I would also like to be able to use the staff/student switch in LMS to switch between staff and student views, similar to what course staff can do in regular courses.

**Comment by pdpinch** [comment]
Question: What role should the CCX coach be assigned when they are added to the CCX.

**Comment by pdpinch** [comment]
The CCX coach should be assigned a staff role in the CCX, to address #88

**Comment by jamiefolsom** [comment]
@pdpinch I've addressed all Sarina's concerns about this PR but one, having to do with how to retrieve a CCX identifier from a URL. My code works, but she's got questions about how. All checks are passing except bokchoy, which appears to be an unrelated flaky test. Will keep at it tomorrow.

**Comment by jamiefolsom** [comment]
See: https://github.com/edx/edx-platform/pull/10251/
