### ISSUE TITLE
When adding a coach to a master course, enroll the coach

### ISSUE THREAD

**Issue by pdpinch** [mitocw/edx-platform#37]
As a CCX coach, I need to be able to see the courseware that I will be scheduling in my CCXs. Although course staff can manually enroll me in the course, it would be simpler if I could be added automatically when I am made a CCX Coach. 

There isn't an existing course role that fits this requirement perfectly. Student may be too limited, but course staff would alllow the coach to view and change grades on the master course. For this story, the coach should be enrolled as a student -- even if registration has been closed.

**Comment by jamiefolsom** [comment]
Hey @pdpinch, is this reopened to give us something to close when we validate on stage.edx.org? Or is there an issue I missed? Thanks!

**Comment by pdpinch** [comment]
That was my thinking. Although the code is merged, so maybe I'm being too pedantic.

**Comment by jamiefolsom** [comment]
No, that makes sense. Thanks for clarifying!

**Comment by pdpinch** [comment]
Closed via https://github.com/edx/edx-platform/pull/9986
