### ISSUE TITLE
Inaccurate courseware if CCX Coach enrolls instructor of master course

### ISSUE THREAD

**Issue by carsongee** [mitocw/edx-platform#40]
Tested on sandbox2o.mitx.mit.edu

This case is a bit odd.  For some reason if the CCX coach happens to enroll the instructor of the master course in the CCX, the courseware is not accurate.  The instructor can access the CCX from his dashboard as an individual course (as any other CCX student would).  However the courseware is identical to that of the master course and not the specified schedule and courseware of the CCX.

The start and end dates do not reflect the selections the CCX coach made either.

![screen shot 2015-08-03 at 4 07 25 pm](https://cloud.githubusercontent.com/assets/8117756/9046731/d16a9928-39fa-11e5-8c09-2d01d8148f12.png)

![screen shot 2015-08-04 at 11 20 47 am](https://cloud.githubusercontent.com/assets/8117756/9064516/e6225a18-3a9a-11e5-8dc8-f1c95dfc1df4.png)

**Comment by pdpinch** [comment]
I believe this was addressed by edx#11787
