### ISSUE TITLE
Selecting time in CCX Coach Dashboard

### ISSUE THREAD

**Issue by carsongee** [mitocw/edx-platform#42]
I've noticed that you cannot select the times for 'start date' or 'end date'. Therefore, you cannot properly add content via the 'Schedule' tab in the 'CCX Coach Dashboard'

At the moment, you can only select start and end date/time after you add the content.

This was tested on sandbox2o.

![screen shot 2015-07-28 at 3 35 47 pm](https://cloud.githubusercontent.com/assets/8117756/8942001/1505d9d6-3541-11e5-9aa4-36d98318560e.png)

**Comment by pdpinch** [comment]
This was a bug that's been fixed.
