### ISSUE TITLE
CCX: unenrolled students still appear in Student List Management control

### ISSUE THREAD

**Issue by carsongee** [mitocw/edx-platform#43]
When I unenroll or revoke access for a user in the CCX Enrollment tab, the user's name remains in the Student List Management control even though the CCX is no longer available in the user's dashboard.

1. As Coach revoke access of a CCX student.
2. Verify that the student's name remains listed as an enrolled student.
3. As the student, verify that the CCX is no longer in your Dashboard.

**Comment by pdpinch** [comment]
copied from https://github.com/jazkarta/edx-platform/issues/119

**Comment by pdpinch** [comment]
@amir-qayyum-khan @pwilkins 

This seems to be working for me now on stage.edx.org Did it get fixed when I wasn't looking?

**Comment by amir-qayyum-khan** [comment]
@pdpinch this issue fix was part of my PR (CCX error message PR) and I verified on stage.

**Comment by pdpinch** [comment]
Thanks Amir!

closed via edx#9335
