### ISSUE TITLE
Learning Paths: Start/'Go to this course' just shows an error message via AJAX if student already enrolled in course

### ISSUE THREAD

**Issue by carsongee** [mitocw/edx-platform#44]
from Janine:  "If I go to the Learning Paths page and click on a course, then the Start button, I see message in the upper left stating the Student is already enrolled. Should the start button launch >the course? If the goal is for it to launch the learning path, then the Start button is not in an intuitive location. It should be next to "Courses in this Learning Path"

**Comment by pdpinch** [comment]
This issue was mistakenly copied from the Jazkarta repo.
