### ISSUE TITLE
two different date widgets appear in Chrome

### ISSUE THREAD

**Issue by carsongee** [mitocw/edx-platform#52]
In the Schedule tab, I can get two different date widgets to appear using Chrome.
Steps to reproduce:

1. Select a unit to add to schedule
1. click inside the set date textbox, a date picker appears
1. click the large dropdown icon, the one furthest to the right, a different date picker overlays the first one. 

![dueling-date-widget](https://cloud.githubusercontent.com/assets/145821/6626723/5d03099a-c8cf-11e4-8895-e91f9dadcef4.png)

**Comment by pdpinch** [comment]
Closed via https://github.com/edx/edx-platform/issues/9114
