### ISSUE TITLE
textbox date doesn't match widget date

### ISSUE THREAD

**Issue by carsongee** [mitocw/edx-platform#55]
This is a nit and I assume that the validation will do its job, but this looks amateurish.  Is the year 2001 or 0001?

![chrome-time-picker](https://cloud.githubusercontent.com/assets/145821/5767904/f5b78cf0-9cd9-11e4-99a3-4e95ad08a2f2.png)

**Comment by amir-qayyum-khan** [comment]
Hi @pdpinch @carsongee 

I fixed this issue in one of my accessibility https://github.com/edx/edx-platform/pull/9114.

##### Steps to verify it are:

- Enter Date like for example 0001-09-28
- You can see calendar is open
![screen shot 2015-09-28 at 6 26 30 pm](https://cloud.githubusercontent.com/assets/10431250/10136655/ff50d3e4-660e-11e5-8ea8-212d04b9bf17.png)
- Now focus out from text field. You can see it correct it to 2001-09-28
![screen shot 2015-09-28 at 6 26 37 pm](https://cloud.githubusercontent.com/assets/10431250/10136675/215229ac-660f-11e5-88ec-e8aa0be2264e.png)

 Thanks,

**Comment by pdpinch** [comment]
@pwilkins can you review this?

(you submitted the issue originally as https://github.com/jazkarta/edx-platform/issues/30)

**Comment by pwilkins** [comment]
I can reproduce this issue on edge.
