### ISSUE TITLE
Schedule tab: active start date is not displayed

### ISSUE THREAD

**Issue by carsongee** [mitocw/edx-platform#56]
Adding new courseware in the CCX Dashboard Schedule tab sets the release date/time to the date it was added to the CCX Schedule, though this date/time is not displayed as the start date in the Schedule tab.  This implies that the start date may be undefined.  This is misleading.  The start date should be displayed.

**Comment by pdpinch** [comment]
@amir-qayyum-khan is this fixed by https://github.com/edx/edx-platform/pull/10353 ?

**Comment by amir-qayyum-khan** [comment]
@pdpinch I am not sure on this one. need to test it.

**Comment by amir-qayyum-khan** [comment]
Done with testing. Yes it is resolve by https://github.com/edx/edx-platform/pull/10353.
I am adding this to cover letter.

- Now ccx schedule import dates from master course if coach has not override them.
- On studio default release date is ```course start date```.
- So by default ccx schedule has release date set to course start date from master course.

![screen shot 2015-10-28 at 2 54 07 pm](https://cloud.githubusercontent.com/assets/10431250/10785194/3cb784d0-7d84-11e5-876b-0c11ff8660f9.png)
