### ISSUE TITLE
Add scrollbars to gradebook

### ISSUE THREAD

**Issue by pdpinch** [mitocw/edx-platform#61]
As a CCX Coach, I need an intuitive way to scroll through a gradebook with a large number of assignments. 

> We had a CCX coach ask us how to view the rest of the gradebook since only part of it can be shown at once. The answer is “Drag it”.

> Suggestion: Change dragging mechanism to scrolling, which people are probably more familiar with for tables.

**Comment by pdpinch** [comment]
I had forgotten this, but just confirmed that we're using a copy of the edX default gradebook. Before we start changing our (forked) code for this gradebook ui, we should probably resolve #35 first.

**Comment by amir-qayyum-khan** [comment]
@pdpinch We are direct rendering edX gradebook code on EdX platform. 
Please see https://github.com/edx/edx-platform/blob/master/lms/djangoapps/ccx/views.py#L557

**If you want me to perform these changes then I need to alter ``courseware/gradebook``** I dont know it sounds Ok ?

**Comment by pdpinch** [comment]
Huh. That must have changed somewhere. I'll have to float this with edX before we start work on it. 

I don't think we need to resolve #35 any more.

**Comment by pdpinch** [comment]
Have at it @amir-qayyum-khan 

See https://openedx.atlassian.net/browse/CRI-42

**Comment by pdpinch** [comment]
closed via https://github.com/edx/edx-platform/pull/10021
