### ISSUE TITLE
Show a block's display_name on hover in the gradebook

### ISSUE THREAD

**Issue by pdpinch** [mitocw/edx-platform#62]
As a CCX Coach, I find the column labels in the gradebook (e.g. "HW03") obscure. I'd like a way to be able to see exactly which problem my student had done to get that grade. 
﻿
<img width="1027" alt="screen shot 2015-08-14 at 4 06 39 pm" src="https://cloud.githubusercontent.com/assets/430126/9283033/7bbd4280-429e-11e5-8bc8-602b3f41f951.png">

One solution would be to show the display_name of the relevant xblock/xmodule when hovering over the column header.

**Comment by pdpinch** [comment]
Again, we are using a fork of the standard edX gradebook code. We should resolve #35 before doing any work on this.

**Comment by amir-qayyum-khan** [comment]
@pdpinch we are not forking standard edX gradebook code. We are direct rendering it. 
Please see https://github.com/edx/edx-platform/blob/master/lms/djangoapps/ccx/views.py#L557

**If you want me to perform these changes the I need to alter ``courseware/gradebook`` ** I dont know it sounds Ok ?

**Comment by pdpinch** [comment]
Thanks Amir. I didn't know that. I'll need to float the idea with edX.

**Comment by pdpinch** [comment]
Have at it, @amir-qayyum-khan 

See https://openedx.atlassian.net/browse/CRI-42

**Comment by amir-qayyum-khan** [comment]
@pdpinch i address tooltip issue with scroll issue.
Please create a new ticket for pagination.

**Comment by pdpinch** [comment]
Can you do some before/after screenshots? I'll try to stand this up myself (Brandon is on vacation), but we'll need screenshots for the edX PR anyway.

**Comment by amir-qayyum-khan** [comment]
Already attached screenshots on PR,  As you can see i made one PR for #61
and #62.
There are three images on PR which show
- Scroll left to right
- Tool tip on two different record for same course.

**Comment by pdpinch** [comment]
closed via https://github.com/edx/edx-platform/pull/10021
