### ISSUE TITLE
fix URL, course title in CCX enrollment email 

### ISSUE THREAD

**Issue by pdpinch** [mitocw/edx-platform#67]
via [Zendesk #2301](https://odl.zendesk.com/agent/tickets/2301)

> Hi Peter,
> Today when I enroll students in my test CCX, the notification email uses the base course name and the link points to the base course, not to the CCX. See example message below:

> If possible, this bug seems important to fix quickly—a smooth enrollment process will probably be important for successful teacher adoption.

> Dear Christopher Chudzicki

> You have been enrolled in Chris Playground 103 at edge.edx.org by a member of the course staff. The course should now appear on your edge.edx.org dashboard.

> To start accessing course materials, please visit https://edge.edx.org/courses/course-v1:CAC+CAC103+FOREVER/

> "Chris Playground 103" is the base course name
https://edge.edx.org/courses/course-v1:CAC+CAC103+FOREVER/ is base course link

> Should be <CCX Name> and <CCX Link> (+ccx@48 in my case).

Best,
Chris

**Comment by pdpinch** [comment]
I'm not sure if this is still using the CCX template:

https://github.com/edx/edx-platform/blob/master/lms/templates/ccx/enroll_email_enrolledmessage.txt

or if it's using the standard enrollment e-mail template:

https://github.com/edx/edx-platform/blob/master/lms/templates/emails/enroll_email_enrolledmessage.txt

Or maybe neither...

**Comment by pdpinch** [comment]
There may be other e-mail templates that need updating as well.

**Comment by amir-qayyum-khan** [comment]
yes **CCX** is now using same templates as **Instructor**
https://github.com/edx/edx-platform/blob/master/lms/djangoapps/instructor/enrollment.py#L361

I made a pr and override email params for CCX for correct CCX course name and url.

**Comment by pdpinch** [comment]
It seems to me that we should be overriding the course display_name when the CCX is created, with the name of the CCX. Is there any reason why we aren't doing that?

See https://github.com/edx/edx-platform/blob/845e1d62966011be1efc86d673fd8749b0c980d8/lms/djangoapps/ccx/views.py#L144-L184

Theoretically, this should address the name part of our e-mail issue.

**Comment by cewing** [comment]
The reason we aren't creating a field override for the course for the display name is because historically that information is stored on the actual CCX object (see [the code here](https://github.com/edx/edx-platform/blob/845e1d62966011be1efc86d673fd8749b0c980d8/lms/djangoapps/ccx/views.py#L162) for where that is done).  I don't expect that there's much reason not to also (or perhaps even only) override the display_name field on the course object, we just haven't ever done that before.

**Comment by pdpinch** [comment]
@amir-qayyum-khan can you try adding an override that sets the course name to the CCX name? And see if that addresses the display_name side of problem?

I'm still confused about the URL....

**Comment by cewing** [comment]
I'm confused now too.  I thought that @amir-qayyum-khan's comment above about a PR to fix the issue had fixed the issue.  Is that not the case?  Is this still an open  problem?

**Comment by pdpinch** [comment]
I was looking for a more stable way to do it than overloading get_email_params()

**Comment by pdpinch** [comment]
https://github.com/edx/edx-platform/issues/9448 has been released (to edge).
We can close this when https://github.com/edx/edx-platform/issues/9475 is merged.

**Comment by pdpinch** [comment]
I know I said we could close this when edx#9475 merged. I think I'll wait until it is released -- hopefully next week.

**Comment by pdpinch** [comment]
Closed via https://github.com/edx/edx-platform/pull/9475
