### ISSUE TITLE
Legacy Dashboard: Course Statistics at a Glance

### ISSUE THREAD

**Issue by pdpinch** [mitocw/edx-platform#71]
As an instructor, I would like to be able to see some high-level information about the content of my course. 

This feature exists in the old legacy instructor dashboard but has not been ported to the new dashboard. It's possible that the relatively new course_structure api (name?) might be easier to use than the way this was originally implemented.

**Comment by sarina** [comment]
What does this give you that you can't get from Studio, Insights, or the Course Info page on the standard dash?

**Comment by pdpinch** [comment]
@itsbenweeks Any thoughts on the value of the legacy "Course Statistics at a Glance" ? I suppose it gives LMS users a way to find out how many video blocks are in a course, but they have to recognize that's what `VideoDescriptorWithMixins` means.

**Comment by sarina** [comment]
I feel like there's a better way via analytics to present a unified view of
course units. It's unclear in these statistics if this means all blocks or
just published blocks, for example.

**Comment by itsbenweeks** [comment]
I agree, @sarina. There haven't been many reports from people who are looking to this feature; and I think that's mainly because of the lack of time-bound data. However, having a few counts of released blocks would be helpful for course staff who already rely on the dashboard for other useful features, such as generating grade reports.

**Comment by sarina** [comment]
I think you guys should either close this issue, or change the topic of the
issue to discuss developing some feature (perhaps in the LMS dash, but
perhaps instead in Studio or Insights) that somehow exposes this data. It's
probably going to invovle an amount of requirements gathering (what is the
feature, for whom is it for, what info do you need), and some preliminary
design, then talking with edx product team to determine the best way to go
-- all prior to beginning implementation.

**Comment by pdpinch** [comment]
Clearly, this hasn't been a priority.
