### ISSUE TITLE
Legacy Dashboard: Course Errors

### ISSUE THREAD

**Issue by pdpinch** [mitocw/edx-platform#72]
As an instructor, I'd like a way to easily see if there are any errors in my course. 

This story has to start with some discovery, as I'm not sure what errors can be reported here, and whether they are useful. 

See https://staging.mitx.mit.edu/courses/DevOps/0.001/2015_Summer/legacy_instructor_dash

![screenshot-staging mitx mit edu 2015-08-21 09-42-26](https://cloud.githubusercontent.com/assets/430126/9409485/021d0a0a-47e9-11e5-95c8-21354b023227.png)

**Comment by sarina** [comment]
Is this feature still even in use? It's unclear to me this is useful at all since the dawn of Studio. This was definitely critical with XML courses and no linter, but we're thankfully way past those days.

**Comment by sarina** [comment]
I think it would be better to spend effort on a linter on studio import time or something.

**Comment by pdpinch** [comment]
Agreed. See https://github.com/mitodl/edxcut
