### ISSUE TITLE
Legacy Dashboard: Download CSV of all responses to a problem

### ISSUE THREAD

**Issue by pdpinch** [mitocw/edx-platform#73]
As an instructor, I'd like to be able to download all the responses to a problem for off-line analysis. It is convenient to do this on-demand from the instructor dashboard so I can act on it while a course is running rather than waiting for summative data after the course is complete. 

See https://staging.mitx.mit.edu/courses/DevOps/0.001/2015_Summer/legacy_instructor_dash

![screenshot-staging mitx mit edu 2015-08-21 09-52-46](https://cloud.githubusercontent.com/assets/430126/9409725/761a61b8-47ea-11e5-9480-1724d9c2a893.png)

This story will require some discovery to make sure that this function isn't already available in the new instructor dashboard, possibly "Data Download" / "Generate Problem Grade Report"

**Comment by pdpinch** [comment]
This was addressed post-Cypress, in https://github.com/edx/edx-platform/commit/df5b2dadda636184116fa394105ea37e3ab3b867

This issue can be closed once the residential release includes this commit, perhaps post-Dogwood.

**Comment by sarina** [comment]
This has been addressed.

![screen shot 2015-12-09 at 9 49 59 am](https://cloud.githubusercontent.com/assets/1985317/11688381/4347a0e0-9e5a-11e5-8dd8-47922c67ff15.png)

**Comment by pdpinch** [comment]
Yep. We'll pick this up with the Dogwood release.

**Comment by pdpinch** [comment]
We picked up this change with the August 2016 update to the MITx residential stack.
