### ISSUE TITLE
Legacy Dashboard: Export Grades to Remote Gradebook

### ISSUE THREAD

**Issue by pdpinch** [mitocw/edx-platform#74]
As an instructor at MIT, I need to be able to export my student's grades to the MIT gradebook.

This works currently in the legacy instructor dashboard. It needs to be moved to the current dashboard, using the same feature flag, with the same functionality. Note that the export has an option to use pre-computed grades. 

![screenshot-staging mitx mit edu 2015-08-21 10-48-53](https://cloud.githubusercontent.com/assets/430126/9411193/9475ad36-47f2-11e5-8711-609dd702c92f.png)

**Comment by pdpinch** [comment]
UC Berkeley may have started some work this summer which approaches the gradebook integration in a different way, exposing a endpoint to pull grades. I'm fairly certain we don't want to do this. I mention it here so that we aren't surprised to be asked about conflicts between these approaches.

**Comment by pdpinch** [comment]
An edX JIRA ticket was opened to discuss this. The proposal was approved and the ticket is closed: https://openedx.atlassian.net/browse/OSPR-179

**Comment by pdpinch** [comment]
There's an old checklist in Trello that may or may not be helpful: https://trello.com/c/G6B3eaHO/24-3-dashboard-port-remote-gradebook-to-the-new-dashboard

**Comment by sarina** [comment]
This would need to be ported; it's only used by MITx.

**Comment by pdpinch** [comment]
done. done. done!
