### ISSUE TITLE
Legacy Dashboard: Pull enrollment data from remote gradebook

### ISSUE THREAD

**Issue by pdpinch** [mitocw/edx-platform#76]
As an instructor, I would like to be able to pull my edX course enrollment from a remote gradebook (i.e. Stellar) or push my edX enrollment. 

There is a UI and set of functions for enrollment in the legacy dashboard, but the UI is confusing and the functions need to be reviewed to make sure they are actually valuable for users. 

![screenshot-staging mitx mit edu 2015-08-21 11-47-28](https://cloud.githubusercontent.com/assets/430126/9412640/d2b942d0-47fa-11e5-97c9-e24ea4c3717b.png)

**Comment by pdpinch** [comment]
@carsongee I know that listing sections and listing students in a section work, but do you know if those functions are actually used by anyone?

**Comment by carsongee** [comment]
I used them to see what users I was about to add to my course and know what sections I had, I think it is is handy to list students, and it would be a nicer experience if we made the section a dropdown populated from the remote API call and got rid of the list sections button

**Comment by sarina** [comment]
This would need to be ported; it's only used by MITx.

**Comment by gsidebo** [comment]
@pdpinch Just based off of the comments here, I'm assuming we don't want/need to reimplement the "Overload enrollment list using remote gradebook" functionality. Seems like we only care about listing students from the remote gradebook. If we really do need the 'overload' functionality, let me know. It's a pretty significant chunk of logic in the legacy codebase.

**Comment by pdpinch** [comment]
Can you leave a comment here with a pointer to the legacy code? 

I don't think it's commonly used so I think we should omit it for now. But if I'm wrong it would be nice to know what you've already discovered.

**Comment by gsidebo** [comment]
This is the function that is called to handle merging/overloading the enrollment list using the remote gradebook: https://github.com/mitodl/edx-platform/blob/mitx/dogwood.3-3/lms/djangoapps/instructor/views/legacy.py#L769. ~150 lines, and it actually creates student enrollments and optionally emails the newly-enrolled students. The code paths to properly enroll/email students may have changed since dogwood

**Comment by pdpinch** [comment]
@NotoriousMKD is checking with faculty to see what functions we need here.

**Comment by pdpinch** [comment]
@gsidebo you took care of this, right?

**Comment by gsidebo** [comment]
Yes, this was implemented in this PR: https://github.com/mitodl/edx-platform/pull/21
