### ISSUE TITLE
Schedule: Date added using right-hand panel assigned unpredictably

### ISSUE THREAD

**Issue by pwilkins** [mitocw/edx-platform#80]
When adding an item to the CCX Schedule from the right panel, the specified start date is assigned to an item unpredictably.  Well, not exactly unpredictably, it must be deterministic, but if there's a rule, it isn't apparent.  It seems to assign the start date to the last non-default item among the section, sub-section, and unit selected.  

So if you select a section and leave sub-section and unit at the default, the date is associated with the section.  If you select a section and sub-section, and leave the unit at the default, the date is associated with the sub-section.  Yup.  There's a pattern here.

**Comment by pdpinch** [comment]
@pwilkins I agree this isn't very user friendly. Do you have any suggestions about what we should do about it?

**Comment by pwilkins** [comment]
I think your proposal of setting a default date of the start date of the master course would resolve this issue.  It might lead to another issue, that multiple dates would need to be change manually, but that is a better problem to solve than this one.

**Comment by amir-qayyum-khan** [comment]
@pdpinch @pwilkins please look into this PR. I think it will solve this issue.
https://github.com/mitocw/edx-platform/pull/99
