### ISSUE TITLE
Schedule tab should display dates for all units that have dates

### ISSUE THREAD

**Issue by pdpinch** [mitocw/edx-platform#85]
inspired by [ZenDesk #2481](https://odl.zendesk.com/agent/tickets/2481):

As an instructor, I would like to see Start Dates and End Dates for all units that have them, not just for the ones that I have set. It's confusing that inherited dates -- either from the master course or from parent units -- are not reflected in the UI. 

<img width="1265" alt="safari-screenshot-lms mitx mit edu 2015-09-11 09-24-47" src="https://p6.zdusercontent.com/attachment/237438/RhxRksXpVTxuqfypXD1A3ZLia?token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..FeLv0jafEYmnWBFd55bVgA.-aTPz0iyWCBWu63CwaXwgeIz1hqAJJ7BX-tfpBL9LVsz1uw6URmcHpK_XgWk1Hj0dIMlvyscKwK_s5lUjUWH7FJH9uDlb_uem8wo6f8gTMZIbMMIdip2p4o6privWA0BmDBshizcXWcZjcD_6qTnjynTpmPO-IPViWC1QOOfsJCY1R6GOJkUcVAvMF_pS9AuyWeyDLEfIYsl_GSsJqq0Ow.ve7s0SOoal1xyW3GTg65bw">

Currently the schedule tab only display dates/times for units that have overrides. If we can, we should pull and display the actual dates for each unit.

**Comment by pwilkins** [comment]
The plan, then, is to set a default start date for schedule items when they are added in the `Schedule` tab, using a date from the master course.  The date used is either the item's start date set in the master course, or if no date is set, the master course's start date.

We can't do the same thing with due dates.  Any suggestions? @pdpinch

**Comment by pdpinch** [comment]
Oy, has this been waiting all this time on me?

I think Amir is addressing this in #99. 

1. Only sequentials/sub-sections have due dates. If there is a date set in the master course, the CCX schedule should display that date until it is overridden. If there is no date in the master course, we can use the "Set date" link text. 

2. All other units' due dates should be labelled N/A

**Comment by amir-qayyum-khan** [comment]
Yes @pdpinch ,
- Unit does not have start and due date of their own. 
- Unit inherits start and due date from subsection.
- if there is no date in subsection then I am showing **Unscheduled** on unit cell because of #51

**Comment by amir-qayyum-khan** [comment]
Fixed via https://github.com/edx/edx-platform/pull/10353
