### ISSUE TITLE
Don't let coaches set due dates for Sections and Units

### ISSUE THREAD

**Issue by pdpinch** [mitocw/edx-platform#86]
As a coach, it's confusing that I can set due dates on section and on units, but those due dates don't appear anywhere for students in lms. 

Currently we let coaches set start dates and due dates on every element in the schedule. However, in studio, course authors can only set due dates on subsections (aka sequentials). It seems like we should follow the Studio convention for consistency. 

While we're at it, we should also display any pre-existing dates from the master course, as these will be applied unless the coach changes them.

**Comment by pwilkins** [comment]
re: "... we should display any pre-existing dates from the master course..."
I'd expect that those dates will pre-date the start date of the CCX.  I propose that we set those dates to the CCX start date.  At least then, they wouldn't all have to be changed.

**Comment by pdpinch** [comment]
Where does the "start date of the CCX" come from? I don't think we allow coaches to set that explicitly. Maybe it's inferred somehow, but I can't remember. 

The important thing is that the schedule UI should reflect the current set of start and due dates. Currently, the coach doesn't know what dates he has inherited from the master course.

**Comment by amir-qayyum-khan** [comment]
@pdpinch do we need start date and due date from a unit. Because in studio only 
- Chapter has start date
- Sequential has start and due date

Unit inherits start and due dates of its sequential (Subsection).

**Comment by pdpinch** [comment]
We should be consistent with studio, but we need to test to be sure that the due dates are enforced. I think there is a bug in this currently.

**Comment by amir-qayyum-khan** [comment]
Ok, let me check.

**Comment by amir-qayyum-khan** [comment]
@pdpinch 
- In **CCX course** I found that after change due date it is visible on courseware, but there is still **check button**. It seems problems are not picking override dates.
![screen shot 2015-10-08 at 1 13 08 pm](https://cloud.githubusercontent.com/assets/10431250/10361039/df147b8c-6dbe-11e5-973b-36c62de6866b.png)
 
- In master course there is no check button.
 ![screen shot 2015-10-08 at 1 16 27 pm](https://cloud.githubusercontent.com/assets/10431250/10361040/df15afe8-6dbe-11e5-9ff8-6341d8bf787a.png)

CC @pwilkins

**Comment by pdpinch** [comment]
Thanks Amir. That's what I found as well. 

However, I was also finding that if I set the due date for the Vertical/Unit then the check button was handled properly. I think Studio must be doing some additional post-processing when users set due dates -- maybe it cascades the date down the tree?

I'll do some more investigation.

**Comment by amir-qayyum-khan** [comment]
@pdpinch This issue in not in scope of my PR. I think we need separate issue for this one. Also I need to review working of problems (code base), Because I have not study it yet.

**Comment by pdpinch** [comment]
Since the only workaround for setting proper dues dates on problems is to use the Unit due date, this issue will have to wait until we resolve #100
