### ISSUE TITLE
Allow coach to view student progress pages

### ISSUE THREAD

**Issue by pdpinch** [mitocw/edx-platform#88]
As a coach, I would like to be able to view my students' progress pages by clicking on their names in the (web) gradebook. 

Currently when I click on their names, I get a page not found error, from a URL like `https://courses.edx.org/courses/ccx-v1:<<CCX locator key>>/progress/<<student id>>`/

This will have to start with some discovery. We omitted progress pages from CCXs early on for simplicity. If we find this has unintended consequeces, we may drop it.

**Comment by giocalitri** [comment]
This is a problem caused by the fact that when a Coach creates a new CCX, the Coach does not get `staff` privileges for the CCX course.

A way to prove this is, in the django shell:

```
In [1]: from opaque_keys.edx.locations import SlashSeparatedCourseKey
In [2]: course_key = SlashSeparatedCourseKey.from_deprecated_string(u'ccx-v1:Organization+CN101+RUN-FALL2015-AGAIN+ccx@2')
In [3]: from student.roles import CourseStaffRole
In [4]: csr = CourseStaffRole(course_key)
In [5]: csr.users_with_role()
Out[5]: []
In [6]: from django.contrib.auth.models import User
In [7]: gio = User.objects.get(username='gio')
In [8]: from instructor.access import allow_access
In [9]: from courseware.courses import get_course_by_id
In [10]: course = get_course_by_id(course_key, None)
In [11]: from courseware.access import has_access
In [12]: has_access(gio, 'staff', course).has_access
Out[12]: False
In [13]: allow_access(course, gio, 'staff')
In [14]: csr.users_with_role()
Out[14]: [<User: gio>]
In [15]: has_access(gio, 'staff', course).has_access
Out[15]: True
```

After this the Coach can access the progress page for his students.

This means that if in #36 we give the Coach `staff` role for his CCX, the problem is solved.

**Comment by pdpinch** [comment]
After further examination, we've found that giving the coach a `staff` role gives her access to too much. We'll need to look for another approach -- either individually adding the coach to certain views, or giving coaches the `staff` role and then removing them from certain views.

**Comment by amir-qayyum-khan** [comment]
Access fixed by PR https://github.com/mitocw/edx-platform/pull/167

**Comment by pdpinch** [comment]
closed via https://github.com/edx/edx-platform/pull/11124
