### ISSUE TITLE
CCX Gradebook download should not return to the browser

### ISSUE THREAD

**Issue by pdpinch** [mitocw/edx-platform#93]
As a coach, I'd like to be able to download the gradebook to a file that I can open in MS Excel -- or, even better, will open in Excel after it is downloaded. 

Currently, the ccx_grades.csv is returned to the browser instead of downloaded:

<img width="925" alt="screen shot 2015-10-02 at 8 46 13 am" src="https://cloud.githubusercontent.com/assets/430126/10246760/12112d28-68e2-11e5-85ee-1d4538e00c39.png">

It appears that Excel will open this csv file, but most users don't know how to properly save it.

**Comment by ShawnMilo** [comment]
[this](http://stackoverflow.com/questions/6544382/csv-file-browser-opens-it-instead-of-downloading) might be helpful. (Set content type and set `'Content-Disposition: attachment;`.)

**Comment by pwilkins** [comment]
Merge request submitted to edX:  Fix CCX grades csv file download #10268
