### ISSUE TITLE
Remote gradebook export should use weighted grades instead of normalized grades

### ISSUE THREAD

**Issue by pdpinch** [mitocw/edx-platform#95]
As an instructor, I would like to have grades submitted to the remote gradebook to be "out of" the max score for the assignment. Grades coming from edX are between 0 and 1.0 and it would be clearer for instructors and students to have them be between 0 and the max score.

- [x] @pdpinch will check with current users to confirm this will be an improvement for everyone, and not just the Math department

**Comment by pdpinch** [comment]
from @pwilkins on https://github.com/mitodl/lmod_proxy/issues/35

> Upon reviewing user requirements, the description of this issue has changed.  The change is that the source of the normalization scaling factor is not Stellar, but edX.  It turns out that course staff want to use edX to weight and scale grades, as presented by the LMS Progress tab. 

> In a nutshell, we intend to identify a source of the grade data, use that source to modify `get_student_grade_summary_data()`[1] in `legacy.py` which is called by `return_csv()`[2] in the same file.
 
> ## 1. Source of grade data
The `edx-submissions` repo contains `api.py`, which contains a `get_scores(course_id, student_id)` function which returns a dict. The key is the assignment ID, and the value is a tuple containing earned points and possible points. This function is called from two places in `lms/djangoapps/courseware/grades.py` to get grades.

> ## 2. Modify the the code that populates the remote gradebook CSV
In `legacy.py`, modify the content of the `datatable` that is passed to `return_csv()`.

> [1] https://github.com/edx/edx-platform/blob/master/lms/djangoapps/instructor/views/legacy.py#L684
> [2] https://github.com/edx/edx-platform/blob/master/lms/djangoapps/instructor/views/legacy.py#L129
> [3] https://github.com/edx/edx-platform/blob/master/lms/djangoapps/instructor/views/legacy.py#L271

**Comment by pdpinch** [comment]
to find out which courses are using remote gradebooks, I trolled through the repo containing our backups

```
git clone https://github.mit.edu/MITx-Studio/Staging-Backup # watch out it's huge
cd  Staging-Backup
find . -path "*2015_Fall*" -name "policy.json" | xargs grep -l fa15 # fa15 is part of the API endpoint for Stellar gradebooks for the Fall 15 semester
```

This gave me a list of 16 courses
```
./MITx...18.03...2015_Fall/policies/2015_Fall/policy.json
./MITx...18.03r_2...2015_Fall/policies/2015_Fall/policy.json
./MITX...18.06r_2...2015_Fall/policies/2015_Fall/policy.json
./MITx...2.001r_1...2015_Fall/policies/2015_Fall/policy.json
./MITx...2.003r_2...2015_Fall/policies/2015_Fall/policy.json
./MITx...2.01r_2...2015_Fall/policies/2015_Fall/policy.json
./MITx...3.014r_1...2015_Fall/policies/2015_Fall/policy.json
./MITx...6.008r...2015_Fall/policies/2015_Fall/policy.json
./MITx...6.832r_1...2015_Fall/policies/2015_Fall/policy.json
./MITx...8.01r-2015_Fall...2015_Fall/policies/2015_Fall/policy.json
./MITx...8.01r_2...2015_Fall/policies/2015_Fall/policy.json
./MITx...8.033r_1...2015_Fall/policies/2015_Fall/policy.json
./MITx...8.05...2015_Fall/policies/2015_Fall/policy.json
./MITx...8.05r...2015_Fall/policies/2015_Fall/policy.json
./MITx...8.13r_3...2015_Fall/policies/2015_Fall/policy.json
./MITx...CC.801_2...2015_Fall/policies/2015_Fall/policy.json
```

Then I used the resulting list to find of courses to find a list of instructors.

**Comment by pwilkins** [comment]
If we should want to make this feature conditional, here are two simple UI solutions, crudely done, to help us visualize the UI:

![screen shot 2015-10-19 at 4 23 20 pm](https://cloud.githubusercontent.com/assets/145821/10613617/e33fbc76-7723-11e5-92cf-90a315f24a1b.png)

One solution is offering a checkbox to indicate preference for normalized grades.
The other solution is to create a new button to export normalized grades.

@pdpinch @ShawnMilo

**Comment by pwilkins** [comment]
I had a conversation with Robin Colodzin, a member of the Learning Modules development team most involved with Gradebook.  She said that LM will accept a score between 0 and 1, and a max score, and do the calculation.  For some reason, I was laboring under the misconception that LM didn't have this capability.  I haven't yet verified this in the code.

**Comment by ShawnMilo** [comment]
That's welcome news. It should help us deliver something sooner.

**Comment by milocast** [comment]
@pwilkins: edX is [waiting](https://github.com/edx/edx-platform/pull/10395#issuecomment-153386160) to hear whether this PR has been pre-reviewed by our team. Please update 10395 if you've done that. Thanks.

**Comment by pwilkins** [comment]
Looking at it now.

**Comment by pwilkins** [comment]
OK.  LGTM.
